regioes_ce = {
    'SUL': ['AURORA', 'BAIXIO', 'BARRO', 'BREJO SANTO', 'FARIAS BRITO',
            'ICO', 'IGUATU', 'IPAUMIRIM', 'JATI',
            'LAVRAS DA MANGABEIRA', 'MILAGRES', 'PENAFORTE',
            'PEREIRO', 'UMARI', 'VARZEA ALEGRE'],

    'OESTE': ['ALTO SANTO', 'ARACOIABA', 'BOA VIAGEM', 'CANINDE',
              'CARIDADE', 'CARIRE', 'IBARETAMA', 'INDEPENDENCIA',
              'IRAUCUBA', 'ITAPAJE', 'ITAPIPOCA', 'ITATIRA',
              'JAGUARIBARA', 'JAGUARIBE', 'LIMOEIRO DO NORTE',
              'MADALENA', 'MILHA', 'OCARA', 'PALHANO',
              'PARAMBU', 'PEDRA BRANCA', 'RUSSAS',
              'SAO JOAO DO JAGUARIBE', 'SAO LUIS DO CURU',
              'SENADOR POMPEU', 'SOLONOPOLE', 'TABULEIRO DO NORTE',
              'TAUA', 'TURURU', 'UMIRIM'],

    'LESTE': ['AQUIRAZ', 'ARACATI', 'BEBERIBE', 'CASCAVEL', 'CAUCAIA',
              'CHOROZINHO', 'EUSEBIO', 'FORTALEZA', 'HORIZONTE',
              'ITAITINGA', 'MARACANAU', 'MARANGUAPE', 'PACAJUS',
              'SAO GONCALO DO AMARANTE'],

    'NORTE': ['ACARAU', 'AMONTADA', 'CAMOCIM', 'BELA CRUZ', 'COREAU',
              'FORQUILHA', 'FRECHEIRINHA', 'ITAREMA', 'MARCO',
              'MORRINHOS', 'SOBRAL', 'TIANGUA', 'UBAJARA'],

}